name: Playwright + Allure

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Select Playwright project (browser)"
        type: choice
        required: true
        default: chromium
        options:
          - chromium
          - firefox
          - webkit

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    name: Run Playwright on ${{ inputs.browser }}
    runs-on: ubuntu-latest

    env:
      # App env (secrets recommended)
      BASE_URL: ${{ secrets.BASE_URL || 'https://www.saucedemo.com' }}
      STD_USER: ${{ secrets.STD_USER }}
      STD_PASS: ${{ secrets.STD_PASS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests (project=${{ inputs.browser }}, retries=2)
        run: npx playwright test --project=${{ inputs.browser }} --retries=2

      # Keep Playwright's own HTML report too
      - name: Upload Playwright HTML report (30 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report-${{ inputs.browser }}
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 30

      # Generate Allure report from allure-results/
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 20

      # Upload Allure report as regular artifact (optional, 30 days)
      - name: Upload Allure report artifact (30 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ inputs.browser }}
          path: allure-report
          retention-days: 30

      # Hand off the Allure static site to GitHub Pages
      - name: Upload artifact for Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    name: Publish Allure to GitHub Pages
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
