name: Playwright + Allure Using Docker Image

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser(s) to execute Playwright tests"
        type: choice
        required: true
        default: chromium
        options: [all, chromium, firefox, webkit]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy

    strategy:
      fail-fast: false
      matrix:
        browser: ${{ fromJSON( inputs.browser == 'all' && '["chromium","firefox","webkit"]' || format('["{0}"]', inputs.browser) ) }}

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      STD_USER: ${{ secrets.STD_USER }}
      STD_PASS: ${{ secrets.STD_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npx playwright test --project=${{ matrix.browser }} --retries=2

      - name: Upload Playwright HTML report (30 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: allure-results
          retention-days: 30
          if-no-files-found: ignore

  allure-report:
    needs: tests
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure results (all browsers)
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: allure-results
          merge-multiple: true

      - name: Generate Allure report (merged)
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 20

      - name: Upload Pages artifact (Allure)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    needs: allure-report
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
