name: Playwright + Allure (docker-fast)

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Playwright project"
        type: choice
        required: true
        default: chromium
        options: [chromium, firefox, webkit]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy 
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      STD_USER: ${{ secrets.STD_USER }}
      STD_PASS: ${{ secrets.STD_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      # Browsers & OS deps are already in the image → no install step

      - name: Run tests
        run: npx playwright test --project=${{ inputs.browser }} --retries=2

      - name: Upload Playwright HTML report (30 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ inputs.browser }}
          path: playwright-report
          retention-days: 30
          if-no-files-found: ignore

      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 20

      - name: Upload Pages artifact (Allure)
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy-pages:
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
